import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  zh: {
    // Header
    'header.home': '首页',
    'header.search.placeholder': '请搜索',
    'header.logout': '退出登录',
    'header.my': '我的',
    
    // Sidebar
    'sidebar.home': '首页',
    'sidebar.courses': '课程/课堂',
    'sidebar.forum': '话题中心',
    'sidebar.livestream': '直播',
    'sidebar.personal': '个人中心',
    'sidebar.membership': '会员中心',
    'sidebar.admin': '管理后台',
    'sidebar.upgrade': '开会员 低至 ¥198',
    
    // Welcome Banner
    'welcome.greeting': '早上好，小明！',
    'welcome.subtitle': '今天是学习的好日子，继续保持您的学习节奏',
    'welcome.becomeTutor': '成为讲师',
    'welcome.fillInfo': '填写资料得奖励',
    'welcome.weeklyGoal': '本周目标',
    'welcome.studyTime': '学习时长 8.5/12h',
    'welcome.studyPoints': '学习积分',
    'welcome.pointsValue': '2,340',
    'welcome.weeklyIncrease': '本周 +120',
    'welcome.checkinDays': '连续打卡',
    'welcome.days': '天',
    'welcome.checkinReward': '再坚持5天获得奖励',
    'welcome.todayTasks': '今日待办',
    'welcome.task.homework': '完成作业：数学练习',
    'welcome.task.video': '观看视频：Python基础',
    'welcome.task.checkin': '今日打卡签到',
    'welcome.complete': '去完成',
    
    // Banner Carousel
    'banner.newSemesterSale.title': '新学期特惠季',
    'banner.newSemesterSale.subtitle': '所有课程享受8折优惠',
    'banner.newSemesterSale.description': '为新学期做好准备，精选课程助你快速提升技能',
    'banner.newSemesterSale.cta': '立即查看',
    'banner.newSemesterSale.tag': '限时优惠',
    
    'banner.aiBootcamp.title': 'AI编程训练营',
    'banner.aiBootcamp.subtitle': '零基础入门人工智能',
    'banner.aiBootcamp.description': '跟随业界专家，掌握AI核心技术和实战项目',
    'banner.aiBootcamp.cta': '免费试学',
    'banner.aiBootcamp.tag': '热门课程',
    
    'banner.challenge.title': '学习成就挑战',
    'banner.challenge.subtitle': '30天学习打卡活动',
    'banner.challenge.description': '坚持学习30天，赢取丰厚奖品和证书',
    'banner.challenge.cta': '参加挑战',
    'banner.challenge.tag': '活动进行中',
    
    'banner.fillInfo.title': '填写资料领奖励',
    'banner.fillInfo.subtitle': '完善个人信息获得积分',
    'banner.fillInfo.description': '填写完整的学习资料，立即获得200积分奖励',
    'banner.fillInfo.cta': '立即填写',
    'banner.fillInfo.tag': '奖励活动',
    
    'banner.lecture.title': '春季编程大讲座',
    'banner.lecture.subtitle': '顶级专家分享最新技术',
    'banner.lecture.description': '邀请业界顶尖专家，分享前沿技术和实战经验',
    'banner.lecture.cta': '立即报名',
    'banner.lecture.tag': '专家讲座',
    
    'banner.contest.title': '春季编程挑战赛',
    'banner.contest.subtitle': '展现你的编程实力',
    'banner.contest.description': '参与编程竞赛，与全国高手同台竞技，赢取丰厚奖品',
    'banner.contest.cta': '报名参赛',
    'banner.contest.tag': '竞赛活动',
    
    'banner.learnMore': '了解详情',
    
    // Course Section
    'course.myCourses': '我的课程',
    'course.clubCourses': '俱乐部课程',
    'course.oneOnOneTutor': '1V1导师',
    'course.specialLectures': '专题讲座',
    'course.liveNow': '直播中',
    'course.upcoming': '即将开始',
    'course.inProgress': '进行中',
    'course.free': '免费',
    'course.participants': '人参与',
    'course.online': '人在线',
    
    // Registration
    'register.title': '注册账户',
    'register.subtitle': '加入Tutorloop在线学习平台',
    'register.email': '邮箱',
    'register.school': '学校',
    'register.grade': '年级',
    'register.age': '年龄',
    'register.phone': '手机号',
    'register.address': '邮寄地址',
    'register.submit': '注册',
    'register.login': '已有账户？立即登录',
    
    // Personal Info Modal
    'profile.title': '个人信息',
    'profile.name': '姓名',
    'profile.email': '邮箱',
    'profile.phone': '手机号',
    'profile.school': '学校',
    'profile.grade': '年级',
    'profile.address': '地址',
    'profile.edit': '编辑资料',
    'profile.close': '关闭',
    
    // Footer (original)
    'footer.progress': 'PROGRESS',
    'footer.follow': 'FOLLOW',
    'footer.contact': 'CONTACT',
    
    // Buttons
    'button.viewDetails': '查看详情',
    'button.joinLive': '加入直播',
    'button.enroll': '立即报名',
    'button.continue': '继续学习',
    'button.submit': '确认提交',
    'button.cancel': '取消',
    'button.save': '保存',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '出错了',
    'common.success': '成功',
    'common.confirm': '确认',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.finish': '完成',
    
    // Homepage
    'home.hero.badge': '个性化学习体验',
    'home.hero.title.start': '开启您的',
    'home.hero.title.learning': '在线学习',
    'home.hero.title.journey': '之旅',
    'home.hero.subtitle': '与全球50,000+学习者一起，通过我们的实战课程掌握核心技能，获得1对1指导和认证，让学习变得高效且有趣。',
    'home.hero.startLearning': '免费开始学习',
    'home.hero.watchVideo': '观看介绍视频',
    'home.stats.students': '活跃学员',
    'home.stats.courses': '精品课程',
    'home.stats.rating': '平均评分',
    
    'home.clubCourses.title': '俱乐部课程',
    'home.clubCourses.subtitle': '加入学习俱乐部，与同学一起进步，享受免费的集体学习体验',
    'home.oneOnOne.title': '1V1导师',
    'home.oneOnOne.subtitle': '专业导师一对一指导，个性化学习方案，快速突破学习瓶颈',
    'home.lectures.title': '专题讲座',
    'home.lectures.subtitle': '行业专家分享前沿知识，拓宽视野，把握行业发展趋势',
    
    'home.cta.title': '准备好开始您的学习之旅了吗？',
    'home.cta.subtitle': '加入我们的学习社区，与全球学员一起成长，掌握未来必备技能',
    'home.cta.register': '立即免费注册',
    'home.cta.learnMore': '了解更多课程',
    'home.cta.gift': '新用户注册即送价值 ¥299 的精品课程',
    
    // Student Stories
    'home.studentStories.title': '学员成功故事',
    'home.studentStories.subtitle': '看看我们的学员如何通过学习改变人生',
    'home.studentStories.student1.name': '李小明',
    'home.studentStories.student1.role': '从零基础到数据分析师',
    'home.studentStories.student1.content': '通过3个月的学习，我成功转行成为数据分析师，薪资提升了60%。',
    'home.studentStories.student1.company': '阿里巴巴',
    'home.studentStories.student2.name': '张小花',
    'home.studentStories.student2.role': '高中生考入清华',
    'home.studentStories.student2.content': '数学成绩从60分提升到145分，最终考入清华大学计算机系。',
    'home.studentStories.student2.company': '清华大学',
    'home.studentStories.student3.name': '王小强',
    'home.studentStories.student3.role': '创业者技能提升',
    'home.studentStories.student3.content': '学会了编程和数据分析，为我的创业项目提供了技术支持。',
    'home.studentStories.student3.company': '自主创业',
    
    // Footer (updated)
    'footer.progress.new': 'Progress',
    'footer.contact.new': 'CONTACT',
    'footer.email': '联系邮箱',
    'footer.terms': 'Terms of Service',
    'footer.conditions': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.safety': 'Trust & Safety',
    
    // Login page
    'login.title': '欢迎登录Tutorloop在线学习平台',
    'login.role': '角色',
    'login.selectRole': '请选择角色',
    'login.student': '学生',
    'login.parent': '家长',
    'login.mobile': '手机号',
    'login.mobilePlaceholder': '请输入手机号',
    'login.verifyCode': '验证码',
    'login.verifyCodePlaceholder': '请输入验证码',
    'login.submit': '立即登录',
    
    // Register page placeholders
    'register.emailPlaceholder': 'example@email.com',
    'register.schoolPlaceholder': '学校名称',
    'register.gradePlaceholder': '年级',
    'register.agePlaceholder': '年龄',
    'register.phonePlaceholder': '手机号码',
    'register.addressPlaceholder': '邮寄地址',
    
    // Dashboard - Limited Time Offers & Hot Recommendations
    'dashboard.limitedOffers.title': '限时优惠',
    'dashboard.limitedOffers.subtitle': '精选课程特价中',
    'dashboard.hotRecommendations.title': '热门推荐',
    'dashboard.hotRecommendations.subtitle': '为您推荐热门课程',
    
    // Course page
    'course.allCourses': '全部课程',
    'course.allLiveStreams': '全部直播',
    'course.learnSketch': 'Learn sketch',
    'course.fromScratchToBuild': 'from scratch to build web',
    'course.courseTitle': '课程标题',
    'course.instructor': '讲师',
    'course.students': '学生',
    'course.rating': '评分',
    'course.price': '价格',
    'course.status': '状态',
    'course.ended': '已结束',
    'course.description': '课程描述',
    'course.algebra2Lab': '代数2学习实验室',
    'course.computerEngineering': '计算机工程',
    'course.biology': '生物学',
    'course.dataStatistics': '数据统计',
    'course.algebra2Description': '探索代数 2 学习实验室概念难懂？依靠同伴辅导来提升学习进度',
    'course.computerDescription': 'Learn Php Codeigniter and understand working with MVC and HMVC from zero to hero',
    'course.biologyDescription': 'Build a RESTful API for a market system using Laravel and dominates the challenging RESTful skills',
    'course.statisticsDescription': 'Dive in and learn React 16.8 from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js',
    'course.participantsEnrolled': '人报名',
    'course.participantsJoined': '人参与',
    'course.liveStreamTitle': 'Learn sketch from scratch to build web design',
    'course.liveStreamSubtitle': 'from scratch to build web',
    'course.designPrinciples': 'Learn design principles for modern web applications',
    'course.reactPatterns': 'Advanced React patterns and best practices',
    
    // Forum page
    'forum.topicCenter': '话题中心',
    'forum.all': '全部',
    'forum.latest': '最新',
    'forum.hot': '最热',
    'forum.createTopic': '发起话题讨论',
    'forum.specialClubs': '专区俱乐部',
    'forum.allDiscussions': '全部讨论',
    'forum.hotTags': '热门标签',
    'forum.latestContent': '最新话题内容',
    'forum.hotContent': '热门话题内容',
    
    // Personal Center
    'personal.myCourses': '我的课程',
    'personal.discussions': '参与的讨论', 
    'personal.favorites': '我的收藏',
    'personal.points': '我的积分',
    'personal.following': '我的关注',
    'personal.teaching': '我的课时',
    'personal.status': '状态',
    'personal.category': '分类',
    'personal.allStatus': '全部',
    'personal.notStarted': '未开始',
    'personal.inProgress': '进行中',
    'personal.completed': '已完成',
    'personal.allCategory': '全部',
    'personal.algebra': '代数',
    'personal.computer': '计算机',
    'personal.statistics': '统计学',
    'personal.programming': '代码程序',
    'personal.allFollowing': '全部关注',
    'personal.unfollow': '取消关注',
    'personal.userInfo': '用户信息',
    'personal.education': '教育',
    'personal.addNew': '新增',
    'personal.certificates': '证书',
    'personal.edit': '编辑',
    'personal.achievement': '成就',
    'personal.completedAll': '完成全部',
    'personal.studyExpert': '学习达人',
    'personal.honorCertificate': '承荣证书',
    
    // Membership page
    'membership.title': '开会员',
    'membership.subtitle': '订阅Tutorloop,解锁更多权益',
    'membership.free': '免费',
    'membership.forever': '永久',
    'membership.currentPlan': '当前套餐',
    'membership.paidVersion': '收费版',
    'membership.monthly': '每月',
    'membership.quarterly': '每季',
    'membership.yearly': '每年',
    'membership.monthlyPlan': '包月',
    'membership.quarterlyPlan': '包季',
    'membership.yearlyPlan': '包年',
    'membership.recommended': '推荐',
    'membership.canCancel': '包月可随时取消',
    'membership.orderNow': '立即订购',
    'membership.paymentTitle': '支付订单',
    'membership.qrCode': '二维码',
    'membership.scanToPay': '扫码支付',
    'membership.paymentDesc': '请使用微信或支付宝扫码支付',
    'membership.cancelPayment': '取消支付',
    'membership.paymentComplete': '支付完成',
    'membership.successMessage': '开通会员成功！',
    
    // Admin Dashboard
    'admin.dashboard.title': '管理后台',
    'admin.dashboard.overview': '概览',
    'admin.dashboard.users': '用户管理',
    'admin.dashboard.courses': '课程管理',
    'admin.dashboard.topics': '话题管理',
    'admin.dashboard.reviews': '审核管理',
    'admin.stats.totalUsers': '总用户数',
    'admin.stats.totalCourses': '总课程数',
    'admin.stats.activeDiscussions': '活跃讨论',
    'admin.stats.todayVisits': '今日访问',
    'admin.users.name': '姓名',
    'admin.users.email': '邮箱',
    'admin.users.role': '角色',
    'admin.users.status': '状态',
    'admin.users.courses': '课程数',
    'admin.users.lastLogin': '最后登录',
    'admin.users.verified': '认证状态',
    'admin.courses.title': '课程标题',
    'admin.courses.instructor': '讲师',
    'admin.courses.students': '学生数',
    'admin.courses.status': '状态',
    'admin.courses.price': '价格',
    'admin.courses.type': '类型',
    'admin.courses.difficulty': '难度',
    'admin.courses.category': '分类',
    'admin.courses.completion': '完成率',
    'admin.topics.title': '话题标题',
    'admin.topics.author': '作者',
    'admin.topics.category': '分类',
    'admin.topics.replies': '回复数',
    'admin.topics.status': '状态',
    'admin.topics.reports': '举报数',
    'admin.topics.views': '浏览量',
    'admin.topics.created': '创建时间',
    'admin.reviews.type': '类型',
    'admin.reviews.title': '标题',
    'admin.reviews.author': '作者',
    'admin.reviews.reports': '举报数',
    'admin.reviews.severity': '严重程度',
    
    // Forum
    'forum.discussions.title': '话题讨论',
    'forum.discussions.author': '作者',
    'forum.discussions.time': '时间',
    'forum.discussions.content': '内容',
    'forum.discussions.likes': '点赞',
    'forum.discussions.dislikes': '点踩',
    'forum.discussions.replies': '回复',
    'forum.discussions.views': '浏览',
    'forum.discussions.badge': '标签',
    'forum.discussions.category': '分类',
    'forum.discussions.tags': '标签',
    'forum.categories.algebra': '代数',
    'forum.categories.geometry': '几何学',
    'forum.categories.sat': 'SAT',
    'forum.categories.biology': '生物学',
    'forum.categories.physics': '物理学',
    'forum.categories.statistics': '统计数据',
    'forum.categories.calculus': '微积分实验室',
    'forum.tags.algebra': '代数',
    'forum.tags.calculus': '微积分',
    'forum.tags.physics': '物理',
    'forum.tags.bug': 'bug',
    'forum.tags.artboard': 'artboard',
    'forum.tags.text': 'text',
    'forum.tags.export': 'export',
    'forum.tags.override': 'override',
    'forum.tags.craft': 'craft',
    'forum.tags.sketchPlugin': 'sketch plugin',
    'forum.tags.error404': 'error 404',
    'forum.tags.angular': 'angular',
    'forum.tags.bootstrap': 'bootstrap',
    'forum.tags.html5': 'html 5',
    'forum.tags.css3': 'css 3',
    'forum.tags.javascript': 'javascript',
    'forum.tags.workflow': 'workflow',
    'forum.tags.update': 'update',
    
    // Course Filters
    'courseFilters.allDifficulty': '全部难易度',
    'courseFilters.g1to5': 'G1-5',
    'courseFilters.g6to8': 'G6-8',
    'courseFilters.g9to12': 'G9-12',
    'courseFilters.allSubject': '全部课程类别',
    'courseFilters.english': '英语',
    'courseFilters.math': '数学',
    'courseFilters.science': '科学',
    'courseFilters.economics': '经济',
    'courseFilters.humanities': '人文',
    'courseFilters.allTime': '课程时间段',
    'courseFilters.morning': '7:00-9:00',
    'courseFilters.afternoon': '16:00-19:00',
    'courseFilters.evening': '19:00-22:00',
    'courseFilters.allLanguage': '授课语言',
    'courseFilters.chinese': '中文',
    'courseFilters.french': '法语',
    'courseFilters.german': '德语',
    'courseFilters.spanish': '西班牙语',
    'courseFilters.italian': '意大利语',
    'courseFilters.japanese': '日语',
    'courseFilters.korean': '韩语',
    
    // User Info
    'userInfo.becomeTutor': '成为一名讲师',
    'userInfo.courseAnalysis': '我做的课程分析',
    'userInfo.personalData': '我做的个数据',
    'userInfo.fixedData': '固定了几个数据',
    'userInfo.completedData': '完成不个数字',
    
    // Welcome
    // 'welcome.todayTasks': '待办任务',
    // 'welcome.complete': '去完成',
    

    
    // Event
    'event.name': '姓名',
    'event.email': '邮箱',
    'event.phone': '手机号',
    'event.skill': '编程技能',
    'event.experience': '编程经验',
    'event.reason': '参赛理由',
    'event.cancel': '取消',
    'event.confirm': '确认报名',
    'event.success': '报名成功！我们会尽快联系您',
    
    // Points
    'points.totalPoints': '全部积分',
    'points.checkinPoints': '上课打卡器',
    'points.teachingPoints': '教授课时',
    'points.checkinDays': '打卡天数统计',
    'points.course': '课程',
    'points.task': '任务',
    'points.date': '日期',
    'points.points': '积分',
    'points.status': '状态',
    'points.attending': '上课',
    'points.answering': '答题',
    'points.tasking': '做任务',
    'points.answeringQuestion': '回答问题',
    'points.systemHomework': '系统作业',
    
    // Teaching
    'teaching.totalClasses': '总课时',
    'teaching.totalHours': '总小时',
    'teaching.totalStudents': '总学生',
    'teaching.course': '课程',
    'teaching.task': '任务',
    'teaching.date': '日期',
    'teaching.points': '积分',
    'teaching.status': '状态',
    
    // Info Collection
    'infoCollection.title': '为了更好的体验Tutorloop，请完善您在平台的个人信息',
    'infoCollection.step1': '第一步',
    'infoCollection.step2': '第二步',
    'infoCollection.step3': '第三步',
    'infoCollection.name': '姓名',
    'infoCollection.email': '邮箱',
    'infoCollection.phone': '手机号',
    'infoCollection.school': '学校',
    'infoCollection.grade': '年级',
    'infoCollection.address': '邮寄地址',
    'infoCollection.subjects': '感兴趣的学科 (可多选)',
    'infoCollection.studyPreferences': '学习偏好',
    'infoCollection.studyPreferencesDesc': '告诉我们您的学习兴趣和习惯',
    'infoCollection.studyGoals': '学习目标',
    'infoCollection.studyGoalsDesc': '最后，告诉我们您的学习期望',
    'infoCollection.studyTime': '每天可用于学习的时间',
    'infoCollection.preferredFormat': '偏好的学习方式',
    'infoCollection.experience': '在线学习经验',
    'infoCollection.expectations': '您希望通过平台获得什么 (可多选)',
    'infoCollection.next': '下一步',
    'infoCollection.skip': '跳过',
    'infoCollection.complete': '完成',
    'infoCollection.submit': '确认提交',
    'infoCollection.success': '信息收集完成，欢迎加入学习平台！',
    
    // Subjects
    'subjects.math': '数学',
    'subjects.physics': '物理',
    'subjects.chemistry': '化学',
    'subjects.biology': '生物',
    'subjects.chinese': '语文',
    'subjects.english': '英语',
    'subjects.history': '历史',
    'subjects.geography': '地理',
    'subjects.politics': '政治',
    'subjects.computer': '计算机',
    'subjects.art': '艺术',
    'subjects.sports': '体育',
    
    // Expectations
    'expectations.improveGrades': '提高学习成绩',
    'expectations.cultivateInterest': '培养学习兴趣',
    'expectations.prepareExam': '准备升学考试',
    'expectations.expandKnowledge': '扩展知识面',
    'expectations.enhanceThinking': '提升思维能力',
    'expectations.makeFriends': '结交学习伙伴',
    
    // Admin Login
    'adminLogin.title': '管理后台登录',
    'adminLogin.subtitle': 'Online Studies 教育管理系统',
    'adminLogin.username': '用户名',
    'adminLogin.usernamePlaceholder': '请输入管理员账号',
    'adminLogin.password': '密码',
    'adminLogin.passwordPlaceholder': '请输入密码',
    'adminLogin.login': '登录',
    'adminLogin.loggingIn': '登录中...',
    'adminLogin.backToFront': '返回前台',
    'adminLogin.success': '登录成功',
    'adminLogin.welcome': '欢迎进入管理后台',
    'adminLogin.failed': '登录失败',
    'adminLogin.wrongCredentials': '用户名或密码错误',
    
    // Toast Messages
    'toast.success': '成功',
    'toast.error': '错误',
    'toast.info': '信息',
    'toast.warning': '警告',
    'toast.profileUpdated': '个人信息已更新',
    'toast.infoCollected': '信息收集完成，欢迎加入学习平台！',
    'toast.topicCreated': '话题发布成功！',
    'toast.clubJoined': '已加入{clubName}俱乐部',
    'toast.clubLeft': '已退出{clubName}俱乐部',
    'toast.favoriteAdded': '已添加到收藏',
    'toast.favoriteRemoved': '已取消收藏',
    'toast.followed': '已关注',
    'toast.unfollowed': '已取消关注',
    'toast.membershipActivated': '会员激活成功！',
    
    // Common Status
    'status.active': '活跃',
    'status.inactive': '非活跃',
    'status.banned': '禁用',
    'status.draft': '草稿',
    'status.published': '已发布',
    'status.archived': '已归档',
    'status.scheduled': '已安排',
    'status.live': '直播中',
    'status.ended': '已结束',
    'status.cancelled': '已取消',
    'status.enrolled': '已报名',
    'status.inProgress': '进行中',
    'status.completed': '已完成',
    'status.dropped': '已退课',
    'status.normal': '正常',
    'status.hot': '热门',
    'status.essence': '精华',
    'status.hidden': '隐藏',
    'status.verified': '已认证',
    'status.unverified': '未认证',
    
    // Common Actions
    'actions.view': '查看',
    'actions.edit': '编辑',
    'actions.delete': '删除',
    'actions.create': '创建',
    'actions.save': '保存',
    'actions.cancel': '取消',
    'actions.confirm': '确认',
    'actions.back': '返回',
    'actions.next': '下一步',
    'actions.previous': '上一步',
    'actions.finish': '完成',
    'actions.submit': '提交',
    'actions.login': '登录',
    'actions.logout': '退出登录',
    'actions.register': '注册',
    'actions.enroll': '报名',
    'actions.join': '加入',
    'actions.leave': '离开',
    'actions.follow': '关注',
    'actions.unfollow': '取消关注',
    'actions.favorite': '收藏',
    'actions.unfavorite': '取消收藏',
    'actions.reply': '回复',
    'actions.like': '点赞',
    'actions.dislike': '点踩',
    'actions.share': '分享',
    'actions.report': '举报',
    'actions.pin': '置顶',
    'actions.unpin': '取消置顶',
    'actions.approve': '通过',
    'actions.reject': '拒绝',
    'actions.ban': '禁用',
    'actions.unban': '启用',
    
    // Become Tutor Modal
    'becomeTutor.currentExp': '当前经验值',
    'becomeTutor.expProgress': '加满：积满300经验值可以申请成为小老师哦',
    'becomeTutor.taskRecord': '任务记录',
    'becomeTutor.taskName': '任务名称',
    'becomeTutor.courseName': '主题名称',
    'becomeTutor.instructor': '授课老师',
    'becomeTutor.duration': '上课时长',
    'becomeTutor.experience': '经验值',
    'becomeTutor.date': '日期',
    'becomeTutor.completeTask': '去完成',
    'becomeTutor.task1.name': '任务一',
    'becomeTutor.task1.detail': '上线满15分钟',
    'becomeTutor.task1.note': '一天一次，不叠加',
    'becomeTutor.task2.name': '任务二',
    'becomeTutor.task2.detail': '完整上完一节课',
    'becomeTutor.task2.note': '每个俱乐部限一周一次',
    'becomeTutor.task3.name': '任务三',
    'becomeTutor.task3.detail': '完整参加一次讲座',
    'becomeTutor.task3.note': '次数不限',
    'becomeTutor.task4.name': '任务四',
    'becomeTutor.task4.detail': '完整参加一次VIP专属讲座',
    'becomeTutor.task4.note': '一周仅限一次',
    'becomeTutor.expValue': '经验值 +{exp}',
    'becomeTutor.expNote': '（{note}）',
    
    // Course Card
    'courseCard.difficultyLevel': '难度系数',
    
    // Course Detail Tabs
    'courseDetail.tab.overview': '课程概览',
    'courseDetail.tab.qa': '问答',
    'courseDetail.tab.reviews': '评价',
    'courseDetail.tab.assignments': '作业',
    'courseDetail.tab.downloads': '下载',
    // Course Detail Content
    'courseDetail.introTitle': '课程介绍',
    'courseDetail.infoTitle': '课程信息',
    'courseDetail.info.time': '上课时间',
    'courseDetail.info.method': '授课方式',
    'courseDetail.info.duration': '课时数',
    'courseDetail.info.grade': '适用年级',
    'courseDetail.learnTitle': '你将学到',
    'courseDetail.title': '课程详情',
    'courseDetail.progressTitle': '课程进度',
  },
  en: {
    // Header
    'header.home': 'Home',
    'header.search.placeholder': 'Please search',
    'header.logout': 'Logout',
    'header.my': 'My',
    
    // Sidebar
    'sidebar.home': 'Home',
    'sidebar.courses': 'Courses/Classes',
    'sidebar.forum': 'Discussion Center',
    'sidebar.livestream': 'Live Stream',
    'sidebar.personal': 'Personal Center',
    'sidebar.membership': 'Membership',
    'sidebar.admin': 'Admin Dashboard',
    'sidebar.upgrade': 'Upgrade from ¥198',
    
    // Welcome Banner
    'welcome.greeting': 'Good morning, Xiao Ming!',
    'welcome.subtitle': 'Today is a great day for learning, keep up your study pace',
    'welcome.becomeTutor': 'Become Tutor',
    'welcome.fillInfo': 'Complete Profile for Rewards',
    'welcome.weeklyGoal': 'Weekly Goal',
    'welcome.studyTime': 'Study Time 8.5/12h',
    'welcome.studyPoints': 'Study Points',
    'welcome.pointsValue': '2,340',
    'welcome.weeklyIncrease': 'This week +120',
    'welcome.checkinDays': 'Consecutive Days',
    'welcome.days': 'days',
    'welcome.checkinReward': 'Keep going for 5 more days to get rewards',
    'welcome.todayTasks': 'Today\'s Tasks',
    'welcome.task.homework': 'Complete Homework: Math Practice',
    'welcome.task.video': 'Watch Video: Python Basics',
    'welcome.task.checkin': 'Daily Check-in',
    'welcome.complete': 'Complete',
    
    // Banner Carousel
    'banner.newSemesterSale.title': 'New Semester Sale',
    'banner.newSemesterSale.subtitle': '20% off all courses',
    'banner.newSemesterSale.description': 'Prepare for the new semester with selected courses to rapidly improve your skills',
    'banner.newSemesterSale.cta': 'View Now',
    'banner.newSemesterSale.tag': 'Limited Time Offer',
    
    'banner.aiBootcamp.title': 'AI Programming Bootcamp',
    'banner.aiBootcamp.subtitle': 'AI for Beginners',
    'banner.aiBootcamp.description': 'Follow industry experts to master AI core technologies and practical projects',
    'banner.aiBootcamp.cta': 'Free Trial',
    'banner.aiBootcamp.tag': 'Popular Course',
    
    'banner.challenge.title': 'Learning Achievement Challenge',
    'banner.challenge.subtitle': '30-Day Learning Check-in Activity',
    'banner.challenge.description': 'Study consistently for 30 days and win great prizes and certificates',
    'banner.challenge.cta': 'Join Challenge',
    'banner.challenge.tag': 'Ongoing Activity',
    
    'banner.fillInfo.title': 'Complete Profile for Rewards',
    'banner.fillInfo.subtitle': 'Get points by completing personal information',
    'banner.fillInfo.description': 'Fill out complete learning profile and get 200 points immediately',
    'banner.fillInfo.cta': 'Fill Now',
    'banner.fillInfo.tag': 'Reward Activity',
    
    'banner.lecture.title': 'Spring Programming Lecture',
    'banner.lecture.subtitle': 'Top experts share latest technologies',
    'banner.lecture.description': 'Invite industry top experts to share cutting-edge technologies and practical experience',
    'banner.lecture.cta': 'Register Now',
    'banner.lecture.tag': 'Expert Lecture',
    
    'banner.contest.title': 'Spring Programming Contest',
    'banner.contest.subtitle': 'Show your programming skills',
    'banner.contest.description': 'Participate in programming contests, compete with national experts, and win great prizes',
    'banner.contest.cta': 'Register',
    'banner.contest.tag': 'Contest Activity',
    
    'banner.learnMore': 'Learn More',
    
    // Course Section
    'course.myCourses': 'My Courses',
    'course.clubCourses': 'Club Courses',
    'course.oneOnOneTutor': '1V1 Tutor',
    'course.specialLectures': 'Special Lectures',
    'course.liveNow': 'Live Now',
    'course.upcoming': 'Coming Soon',
    'course.inProgress': 'In Progress',
    'course.free': 'Free',
    'course.participants': ' participants',
    'course.online': ' online',
    
    // Registration
    'register.title': 'Create Account',
    'register.subtitle': 'Join Tutorloop Online Learning Platform',
    'register.email': 'Email',
    'register.school': 'School',
    'register.grade': 'Grade',
    'register.age': 'Age',
    'register.phone': 'Phone',
    'register.address': 'Mailing Address',
    'register.submit': 'Register',
    'register.login': 'Already have an account? Login',
    
    // Personal Info Modal
    'profile.title': 'Personal Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.school': 'School',
    'profile.grade': 'Grade',
    'profile.address': 'Address',
    'profile.edit': 'Edit Profile',
    'profile.close': 'Close',
    
    // Footer
    'footer.progress': 'PROGRESS',
    'footer.follow': 'FOLLOW',
    'footer.contact': 'CONTACT',
    
    // Buttons
    'button.viewDetails': 'View Details',
    'button.joinLive': 'Join Live',
    'button.enroll': 'Enroll Now',
    'button.continue': 'Continue Learning',
    'button.submit': 'Submit',
    'button.cancel': 'Cancel',
    'button.save': 'Save',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error occurred',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    
    // Homepage
    'home.hero.badge': 'Personalized Learning Experience',
    'home.hero.title.start': 'Start Your',
    'home.hero.title.learning': 'Online Learning',
    'home.hero.title.journey': 'Journey',
    'home.hero.subtitle': 'Join 50,000+ learners worldwide, master core skills through our practical courses, get 1-on-1 guidance and certification, making learning efficient and fun.',
    'home.hero.startLearning': 'Start Learning Free',
    'home.hero.watchVideo': 'Watch Intro Video',
    'home.stats.students': 'Active Students',
    'home.stats.courses': 'Premium Courses',
    'home.stats.rating': 'Average Rating',
    
    'home.clubCourses.title': 'Club Courses',
    'home.clubCourses.subtitle': 'Join learning clubs, progress with classmates, enjoy free collaborative learning experiences',
    'home.oneOnOne.title': '1V1 Tutors',
    'home.oneOnOne.subtitle': 'Professional one-on-one tutoring, personalized learning plans, quickly breakthrough learning bottlenecks',
    'home.lectures.title': 'Special Lectures',
    'home.lectures.subtitle': 'Industry experts share cutting-edge knowledge, broaden horizons, grasp industry trends',
    
    'home.cta.title': 'Ready to Start Your Learning Journey?',
    'home.cta.subtitle': 'Join our learning community, grow with global students, master essential future skills',
    'home.cta.register': 'Register Free Now',
    'home.cta.learnMore': 'Learn More Courses',
    'home.cta.gift': '🎁 New users get premium courses worth ¥299 upon registration',
    
    // Student Stories
    'home.studentStories.title': 'Student Success Stories',
    'home.studentStories.subtitle': 'See how our students transform their lives through learning',
    'home.studentStories.student1.name': 'Li Xiaoming',
    'home.studentStories.student1.role': 'From Zero to Data Analyst',
    'home.studentStories.student1.content': 'Through 3 months of study, I successfully transitioned to a data analyst role with a 60% salary increase.',
    'home.studentStories.student1.company': 'Alibaba',
    'home.studentStories.student2.name': 'Zhang Xiaohua',
    'home.studentStories.student2.role': 'High School Student to Tsinghua',
    'home.studentStories.student2.content': 'My math scores improved from 60 to 145, and I was admitted to Tsinghua University Computer Science.',
    'home.studentStories.student2.company': 'Tsinghua University',
    'home.studentStories.student3.name': 'Wang Xiaoqiang',
    'home.studentStories.student3.role': 'Entrepreneur Skill Enhancement',
    'home.studentStories.student3.content': 'I learned programming and data analysis, providing technical support for my startup project.',
    'home.studentStories.student3.company': 'Self-employed',
    
    // Footer (updated)
    'footer.progress.new': 'Progress',
    'footer.contact.new': 'CONTACT',
    'footer.email': 'Contact Email',
    'footer.terms': 'Terms of Service',
    'footer.conditions': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.safety': 'Trust & Safety',
    
    // Login page
    'login.title': 'Welcome to Tutorloop Online Learning Platform',
    'login.role': 'Role',
    'login.selectRole': 'Please select role',
    'login.student': 'Student',
    'login.parent': 'Parent',
    'login.mobile': 'Mobile Phone',
    'login.mobilePlaceholder': 'Please enter mobile phone',
    'login.verifyCode': 'Verification Code',
    'login.verifyCodePlaceholder': 'Please enter verification code',
    'login.submit': 'Login Now',
    
    // Register page placeholders
    'register.emailPlaceholder': 'example@email.com',
    'register.schoolPlaceholder': 'School name',
    'register.gradePlaceholder': 'Grade',
    'register.agePlaceholder': 'Age',
    'register.phonePlaceholder': 'Phone number',
    'register.addressPlaceholder': 'Mailing address',
    
    // Dashboard - Limited Time Offers & Hot Recommendations
    'dashboard.limitedOffers.title': 'Limited Time Offers',
    'dashboard.limitedOffers.subtitle': 'Selected courses on special price',
    'dashboard.hotRecommendations.title': 'Hot Recommendations',
    'dashboard.hotRecommendations.subtitle': 'Recommended popular courses for you',
    
    // Course page
    'course.allCourses': 'All Courses',
    'course.allLiveStreams': 'All Live Streams',
    'course.learnSketch': 'Learn sketch',
    'course.fromScratchToBuild': 'from scratch to build web',
    'course.courseTitle': 'Course Title',
    'course.instructor': 'Instructor',
    'course.students': 'Students',
    'course.rating': 'Rating',
    'course.price': 'Price',
    'course.status': 'Status',
    'course.ended': 'Ended',
    'course.description': 'Course Description',
    'course.algebra2Lab': 'Algebra 2 Learning Lab',
    'course.computerEngineering': 'Computer Engineering',
    'course.biology': 'Biology',
    'course.dataStatistics': 'Data Statistics',
    'course.algebra2Description': 'Exploring Algebra 2 concepts difficult to understand? Rely on peer tutoring to improve learning progress',
    'course.computerDescription': 'Learn Php Codeigniter and understand working with MVC and HMVC from zero to hero',
    'course.biologyDescription': 'Build a RESTful API for a market system using Laravel and dominates the challenging RESTful skills',
    'course.statisticsDescription': 'Dive in and learn React 16.8 from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js',
    'course.participantsEnrolled': ' enrolled',
    'course.participantsJoined': ' joined',
    'course.liveStreamTitle': 'Learn sketch from scratch to build web design',
    'course.liveStreamSubtitle': 'from scratch to build web',
    'course.designPrinciples': 'Learn design principles for modern web applications',
    'course.reactPatterns': 'Advanced React patterns and best practices',
    
    // Forum page
    'forum.topicCenter': 'Discussion Center',
    'forum.all': 'All',
    'forum.latest': 'Latest',
    'forum.hot': 'Hot',
    'forum.createTopic': 'Create Topic Discussion',
    'forum.specialClubs': 'Special Clubs',
    'forum.allDiscussions': 'All Discussions',
    'forum.hotTags': 'Hot Tags',
    'forum.latestContent': 'Latest topic content',
    'forum.hotContent': 'Hot topic content',
    'forum.clubCategories': 'Club Categories',
    'forum.algebra': 'Algebra',
    'forum.geometry': 'Geometry',
    'forum.sat': 'SAT',
    'forum.biology': 'Biology',
    'forum.physics': 'Physics',
    'forum.statistics': 'Statistics',
    'forum.calculus': 'Calculus Lab',
    'forum.discussions': 'Discussions',
    'forum.clubMembers': 'Club Members',
    'forum.joinClub': 'Join Club',
    'forum.leaveClub': 'Leave Club',
    
    // Course Filters
    'courseFilters.allDifficulty': 'All Difficulty',
    'courseFilters.g1to5': 'G1-5',
    'courseFilters.g6to8': 'G6-8',
    'courseFilters.g9to12': 'G9-12',
    'courseFilters.allSubject': 'All Course Categories',
    'courseFilters.english': 'English',
    'courseFilters.math': 'Math',
    'courseFilters.science': 'Science',
    'courseFilters.economics': 'Economics',
    'courseFilters.humanities': 'Humanities',
    'courseFilters.allTime': 'Course Time Slots',
    'courseFilters.morning': '7:00-9:00',
    'courseFilters.afternoon': '16:00-19:00',
    'courseFilters.evening': '19:00-22:00',
    'courseFilters.allLanguage': 'Teaching Language',
    'courseFilters.chinese': 'Chinese',
    'courseFilters.french': 'French',
    'courseFilters.german': 'German',
    'courseFilters.spanish': 'Spanish',
    'courseFilters.italian': 'Italian',
    'courseFilters.japanese': 'Japanese',
    'courseFilters.korean': 'Korean',
    
    // Membership page
    'membership.title': 'Membership',
    'membership.subtitle': 'Subscribe to Tutorloop, unlock more benefits',
    'membership.free': 'Free',
    'membership.forever': 'Forever',
    'membership.currentPlan': 'Current Plan',
    'membership.paidVersion': 'Paid Version',
    'membership.monthly': 'Monthly',
    'membership.quarterly': 'Quarterly', 
    'membership.yearly': 'Yearly',
    'membership.monthlyPlan': 'Monthly Plan',
    'membership.quarterlyPlan': 'Quarterly Plan',
    'membership.yearlyPlan': 'Yearly Plan',
    'membership.recommended': 'Recommended',
    'membership.canCancel': 'Monthly plan can be cancelled anytime',
    'membership.orderNow': 'Order Now',
    'membership.paymentTitle': 'Payment Order',
    'membership.qrCode': 'QR Code',
    'membership.scanToPay': 'Scan to Pay',
    'membership.paymentDesc': 'Please use WeChat or Alipay to scan and pay',
    'membership.cancelPayment': 'Cancel Payment',
    'membership.paymentComplete': 'Payment Complete',
    'membership.successMessage': 'Membership activated successfully!',
    'membership.freeFeatures': 'Free Features',
    'membership.maxClubs': 'Join up to 3 clubs simultaneously',
    'membership.tutorSessions': '1V1 tutor sessions once a week for 30 minutes',
    'membership.lectures': 'University student/industry professional lectures 2 times per year',
    'membership.unlimitedClubs': 'No limit on number of clubs to join',
    'membership.moreTutorSessions': '1V1 tutor sessions 6 times per week for 90 minutes',
    'membership.unlimitedLectures': 'University student/industry professional lectures unlimited times per year',
    'membership.pointsEfficiency': 'Points collection efficiency +1.1x',
    'membership.bonusPoints': 'Bonus 250 points',
    'membership.pointsEfficiency2': 'Points collection efficiency +1.2x',
    'membership.bonusPoints2': 'Bonus 500 points',
    
    // Personal Center
    'personal.myCourses': 'My Courses',
    'personal.discussions': 'Discussions Participated', 
    'personal.favorites': 'My Favorites',
    'personal.points': 'My Points',
    'personal.following': 'My Following',
    'personal.teaching': 'My Teaching Hours',
    'personal.status': 'Status',
    'personal.category': 'Category',
    'personal.allStatus': 'All',
    'personal.notStarted': 'Not Started',
    'personal.inProgress': 'In Progress',
    'personal.completed': 'Completed',
    'personal.allCategory': 'All',
    'personal.algebra': 'Algebra',
    'personal.computer': 'Computer',
    'personal.statistics': 'Statistics',
    'personal.programming': 'Programming',
    'personal.allFollowing': 'All Following',
    'personal.unfollow': 'Unfollow',
    'personal.userInfo': 'User Information',
    'personal.education': 'Education',
    'personal.addNew': 'Add New',
    'personal.certificates': 'Certificates',
    'personal.edit': 'Edit',
    'personal.achievement': 'Achievement',
    'personal.completedAll': 'Complete All',
    'personal.studyExpert': 'Study Expert',
    'personal.honorCertificate': 'Honor Certificate',
    
    // Admin Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.overview': 'Overview',
    'admin.dashboard.users': 'User Management',
    'admin.dashboard.courses': 'Course Management',
    'admin.dashboard.topics': 'Topic Management',
    'admin.dashboard.reviews': 'Review Management',
    'admin.stats.totalUsers': 'Total Users',
    'admin.stats.totalCourses': 'Total Courses',
    'admin.stats.activeDiscussions': 'Active Discussions',
    'admin.stats.todayVisits': 'Today\'s Visits',
    'admin.users.name': 'Name',
    'admin.users.email': 'Email',
    'admin.users.role': 'Role',
    'admin.users.status': 'Status',
    'admin.users.courses': 'Courses',
    'admin.users.lastLogin': 'Last Login',
    'admin.users.verified': 'Verified',
    'admin.courses.title': 'Course Title',
    'admin.courses.instructor': 'Instructor',
    'admin.courses.students': 'Students',
    'admin.courses.status': 'Status',
    'admin.courses.price': 'Price',
    'admin.courses.type': 'Type',
    'admin.courses.difficulty': 'Difficulty',
    'admin.courses.category': 'Category',
    'admin.courses.completion': 'Completion',
    'admin.topics.title': 'Topic Title',
    'admin.topics.author': 'Author',
    'admin.topics.category': 'Category',
    'admin.topics.replies': 'Replies',
    'admin.topics.status': 'Status',
    'admin.topics.reports': 'Reports',
    'admin.topics.views': 'Views',
    'admin.topics.created': 'Created',
    'admin.reviews.type': 'Type',
    'admin.reviews.title': 'Title',
    'admin.reviews.author': 'Author',
    'admin.reviews.reports': 'Reports',
    'admin.reviews.severity': 'Severity',
    
    // Forum
    'forum.discussions.title': 'Topic Discussions',
    'forum.discussions.author': 'Author',
    'forum.discussions.time': 'Time',
    'forum.discussions.content': 'Content',
    'forum.discussions.likes': 'Likes',
    'forum.discussions.dislikes': 'Dislikes',
    'forum.discussions.replies': 'Replies',
    'forum.discussions.views': 'Views',
    'forum.discussions.badge': 'Badge',
    'forum.discussions.category': 'Category',
    'forum.discussions.tags': 'Tags',
    'forum.categories.algebra': 'Algebra',
    'forum.categories.geometry': 'Geometry',
    'forum.categories.sat': 'SAT',
    'forum.categories.biology': 'Biology',
    'forum.categories.physics': 'Physics',
    'forum.categories.statistics': 'Statistics',
    'forum.categories.calculus': 'Calculus Lab',
    'forum.tags.algebra': 'Algebra',
    'forum.tags.calculus': 'Calculus',
    'forum.tags.physics': 'Physics',
    'forum.tags.bug': 'bug',
    'forum.tags.artboard': 'artboard',
    'forum.tags.text': 'text',
    'forum.tags.export': 'export',
    'forum.tags.override': 'override',
    'forum.tags.craft': 'craft',
    'forum.tags.sketchPlugin': 'sketch plugin',
    'forum.tags.error404': 'error 404',
    'forum.tags.angular': 'angular',
    'forum.tags.bootstrap': 'bootstrap',
    'forum.tags.html5': 'html 5',
    'forum.tags.css3': 'css 3',
    'forum.tags.javascript': 'javascript',
    'forum.tags.workflow': 'workflow',
    'forum.tags.update': 'update',
    
    // Course Filters
    // 'courseFilters.allDifficulty': 'All Difficulty',
    // 'courseFilters.g1to5': 'G1-5',
    // 'courseFilters.g6to8': 'G6-8',
    // 'courseFilters.g9to12': 'G9-12',
    // 'courseFilters.allSubject': 'All Course Categories',
    // 'courseFilters.english': 'English',
    // 'courseFilters.math': 'Math',
    // 'courseFilters.science': 'Science',
    // 'courseFilters.economics': 'Economics',
    // 'courseFilters.humanities': 'Humanities',
    // 'courseFilters.allTime': 'Course Time Slots',
    // 'courseFilters.morning': '7:00-9:00',
    // 'courseFilters.afternoon': '16:00-19:00',
    // 'courseFilters.evening': '19:00-22:00',
    // 'courseFilters.allLanguage': 'Teaching Language',
    // 'courseFilters.chinese': 'Chinese',
    // 'courseFilters.french': 'French',
    // 'courseFilters.german': 'German',
    // 'courseFilters.spanish': 'Spanish',
    // 'courseFilters.italian': 'Italian',
    // 'courseFilters.japanese': 'Japanese',
    // 'courseFilters.korean': 'Korean',
    
    // User Info
    'userInfo.becomeTutor': 'Become a Tutor',
    'userInfo.courseAnalysis': 'My Course Analysis',
    'userInfo.personalData': 'My Personal Data',
    'userInfo.fixedData': 'Fixed Data',
    'userInfo.completedData': 'Completed Data',
    
    // Points
    'points.totalPoints': 'Total Points',
    'points.checkinPoints': 'Check-in Points',
    'points.teachingPoints': 'Teaching Points',
    'points.checkinDays': 'Check-in Days',
    'points.course': 'Course',
    'points.task': 'Task',
    'points.date': 'Date',
    'points.points': 'Points',
    'points.status': 'Status',
    'points.attending': 'Attending',
    'points.answering': 'Answering',
    'points.tasking': 'Tasking',
    'points.answeringQuestion': 'Answering Question',
    'points.systemHomework': 'System Homework',
    
    // Teaching
    'teaching.totalClasses': 'Total Classes',
    'teaching.totalHours': 'Total Hours',
    'teaching.totalStudents': 'Total Students',
    'teaching.course': 'Course',
    'teaching.task': 'Task',
    'teaching.date': 'Date',
    'teaching.points': 'Points',
    'teaching.status': 'Status',
    
    // Info Collection
    'infoCollection.title': 'For a better Tutorloop experience, please complete your personal information',
    'infoCollection.step1': 'Step 1',
    'infoCollection.step2': 'Step 2',
    'infoCollection.step3': 'Step 3',
    'infoCollection.name': 'Name',
    'infoCollection.email': 'Email',
    'infoCollection.phone': 'Phone',
    'infoCollection.school': 'School',
    'infoCollection.grade': 'Grade',
    'infoCollection.address': 'Address',
    'infoCollection.subjects': 'Subjects of Interest (Multiple Choice)',
    'infoCollection.studyPreferences': 'Learning Preferences',
    'infoCollection.studyPreferencesDesc': 'Tell us about your learning interests and habits',
    'infoCollection.studyGoals': 'Learning Goals',
    'infoCollection.studyGoalsDesc': 'Finally, tell us about your learning expectations',
    'infoCollection.studyTime': 'Daily Study Time Available',
    'infoCollection.preferredFormat': 'Preferred Learning Format',
    'infoCollection.experience': 'Online Learning Experience',
    'infoCollection.expectations': 'What do you hope to gain from the platform? (Multiple Choice)',
    'infoCollection.next': 'Next',
    'infoCollection.skip': 'Skip',
    'infoCollection.complete': 'Complete',
    'infoCollection.submit': 'Confirm Submit',
    'infoCollection.success': 'Information collection completed, welcome to the learning platform!',
    
    // Subjects
    'subjects.math': 'Math',
    'subjects.physics': 'Physics',
    'subjects.chemistry': 'Chemistry',
    'subjects.biology': 'Biology',
    'subjects.chinese': 'Chinese',
    'subjects.english': 'English',
    'subjects.history': 'History',
    'subjects.geography': 'Geography',
    'subjects.politics': 'Politics',
    'subjects.computer': 'Computer',
    'subjects.art': 'Art',
    'subjects.sports': 'Sports',
    
    // Expectations
    'expectations.improveGrades': 'Improve Academic Performance',
    'expectations.cultivateInterest': 'Cultivate Learning Interest',
    'expectations.prepareExam': 'Prepare for Entrance Exams',
    'expectations.expandKnowledge': 'Expand Knowledge Base',
    'expectations.enhanceThinking': 'Enhance Thinking Skills',
    'expectations.makeFriends': 'Make Learning Friends',
    
    // Admin Login
    'adminLogin.title': 'Admin Login',
    'adminLogin.subtitle': 'Online Studies Education Management System',
    'adminLogin.username': 'Username',
    'adminLogin.usernamePlaceholder': 'Please enter admin account',
    'adminLogin.password': 'Password',
    'adminLogin.passwordPlaceholder': 'Please enter password',
    'adminLogin.login': 'Login',
    'adminLogin.loggingIn': 'Logging in...',
    'adminLogin.backToFront': 'Back to Front',
    'adminLogin.success': 'Login Successful',
    'adminLogin.welcome': 'Welcome to Admin Dashboard',
    'adminLogin.failed': 'Login Failed',
    'adminLogin.wrongCredentials': 'Wrong username or password',
    
    // Toast Messages
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.info': 'Info',
    'toast.warning': 'Warning',
    'toast.profileUpdated': 'Profile updated successfully',
    'toast.infoCollected': 'Information collection completed, welcome to the learning platform!',
    'toast.topicCreated': 'Topic created successfully!',
    'toast.clubJoined': 'Joined {clubName} club',
    'toast.clubLeft': 'Left {clubName} club',
    'toast.favoriteAdded': 'Added to favorites',
    'toast.favoriteRemoved': 'Removed from favorites',
    'toast.followed': 'Followed',
    'toast.unfollowed': 'Unfollowed',
    'toast.membershipActivated': 'Membership activated successfully!',
    
    // Common Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.banned': 'Banned',
    'status.draft': 'Draft',
    'status.published': 'Published',
    'status.archived': 'Archived',
    'status.scheduled': 'Scheduled',
    'status.live': 'Live',
    'status.ended': 'Ended',
    'status.cancelled': 'Cancelled',
    'status.enrolled': 'Enrolled',
    'status.inProgress': 'In Progress',
    'status.completed': 'Completed',
    'status.dropped': 'Dropped',
    'status.normal': 'Normal',
    'status.hot': 'Hot',
    'status.essence': 'Essence',
    'status.hidden': 'Hidden',
    'status.verified': 'Verified',
    'status.unverified': 'Unverified',
    
    // Common Actions
    'actions.view': 'View',
    'actions.edit': 'Edit',
    'actions.delete': 'Delete',
    'actions.create': 'Create',
    'actions.save': 'Save',
    'actions.cancel': 'Cancel',
    'actions.confirm': 'Confirm',
    'actions.back': 'Back',
    'actions.next': 'Next',
    'actions.previous': 'Previous',
    'actions.finish': 'Finish',
    'actions.submit': 'Submit',
    'actions.login': 'Login',
    'actions.logout': 'Logout',
    'actions.register': 'Register',
    'actions.enroll': 'Enroll',
    'actions.join': 'Join',
    'actions.leave': 'Leave',
    'actions.follow': 'Follow',
    'actions.unfollow': 'Unfollow',
    'actions.favorite': 'Favorite',
    'actions.unfavorite': 'Unfavorite',
    'actions.reply': 'Reply',
    'actions.like': 'Like',
    'actions.dislike': 'Dislike',
    'actions.share': 'Share',
    'actions.report': 'Report',
    'actions.pin': 'Pin',
    'actions.unpin': 'Unpin',
    'actions.approve': 'Approve',
    'actions.reject': 'Reject',
    'actions.ban': 'Ban',
    'actions.unban': 'Unban',
    
    // Become Tutor Modal
    'becomeTutor.currentExp': 'Current Experience',
    'becomeTutor.expProgress': 'Fill up: Reach 300 experience points to apply to become a tutor',
    'becomeTutor.taskRecord': 'Task Records',
    'becomeTutor.taskName': 'Task Name',
    'becomeTutor.courseName': 'Course Name',
    'becomeTutor.instructor': 'Instructor',
    'becomeTutor.duration': 'Duration',
    'becomeTutor.experience': 'Experience',
    'becomeTutor.date': 'Date',
    'becomeTutor.completeTask': 'Complete',
    'becomeTutor.task1.name': 'Task 1',
    'becomeTutor.task1.detail': 'Online for 15 minutes',
    'becomeTutor.task1.note': 'Once per day, no stacking',
    'becomeTutor.task2.name': 'Task 2',
    'becomeTutor.task2.detail': 'Complete a full class',
    'becomeTutor.task2.note': 'Once per week per club',
    'becomeTutor.task3.name': 'Task 3',
    'becomeTutor.task3.detail': 'Complete a lecture',
    'becomeTutor.task3.note': 'Unlimited times',
    'becomeTutor.task4.name': 'Task 4',
    'becomeTutor.task4.detail': 'Complete a VIP exclusive lecture',
    'becomeTutor.task4.note': 'Once per week only',
    'becomeTutor.expValue': 'Experience +{exp}',
    'becomeTutor.expNote': '({note})',
    
    // Course Card
    'courseCard.difficultyLevel': 'Difficulty Level',
    
    // Course Detail Tabs
    'courseDetail.tab.overview': 'Overview',
    'courseDetail.tab.qa': 'Q&A',
    'courseDetail.tab.reviews': 'Reviews',
    'courseDetail.tab.assignments': 'Assignments',
    'courseDetail.tab.downloads': 'Downloads',
    // Course Detail Content
    'courseDetail.introTitle': 'Course Introduction',
    'courseDetail.infoTitle': 'Course Info',
    'courseDetail.info.time': 'Time',
    'courseDetail.info.method': 'Method',
    'courseDetail.info.duration': 'Duration',
    'courseDetail.info.grade': 'Grade',
    'courseDetail.learnTitle': 'What You Will Learn',
    'courseDetail.title': 'Course Detail',
    'courseDetail.progressTitle': 'Course Progress',

  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};