// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgxylhdvhjunttweuwzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneHlsaGR2aGp1bnR0d2V1d3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODkwMTMsImV4cCI6MjA2NTk2NTAxM30.eoyx2W-mhVPvQ1ddFOnkcp3M1a-Mz2esWsc9uaycCyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);